# Generated by Django 4.1.3 on 2023-02-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagents',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliveryagents',
            name='pincode',
        ),
    ]
