# Generated by Django 4.1.3 on 2023-02-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_deliveryagents_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
