# Generated by Django 4.1.3 on 2023-02-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categorylist_image_itemlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='delagentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.deliveryagents'),
        ),
    ]
