# Generated by Django 4.1.3 on 2023-02-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_foodorder_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.address'),
        ),
    ]
