# Generated by Django 4.1.3 on 2023-02-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_itemlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemlist'),
        ),
    ]
