# Generated by Django 4.1.3 on 2023-03-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderitem_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='categoryname',
            field=models.CharField(max_length=255),
        ),
    ]
