# Generated by Django 4.1.3 on 2023-03-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_categorylist_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
