# Generated by Django 4.1.3 on 2023-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itemlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
